// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWRgteT2ur1FVpVLCN_BwB1P15lcr1BEs',
    appId: '1:489113225670:web:8180026897e3680d030ac7',
    messagingSenderId: '489113225670',
    projectId: 'appcatatan-258a2',
    authDomain: 'appcatatan-258a2.firebaseapp.com',
    storageBucket: 'appcatatan-258a2.firebasestorage.app',
    measurementId: 'G-H1Z13J269Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRYyxJz1P9I2wt5ghrDQu_Tzp875h9UhY',
    appId: '1:489113225670:android:b3710ee27652e933030ac7',
    messagingSenderId: '489113225670',
    projectId: 'appcatatan-258a2',
    storageBucket: 'appcatatan-258a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYemtN3ijQHnIfGo1o0tjSEfKAqF5_yrY',
    appId: '1:489113225670:ios:da21ea6984e56f80030ac7',
    messagingSenderId: '489113225670',
    projectId: 'appcatatan-258a2',
    storageBucket: 'appcatatan-258a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYemtN3ijQHnIfGo1o0tjSEfKAqF5_yrY',
    appId: '1:489113225670:ios:da21ea6984e56f80030ac7',
    messagingSenderId: '489113225670',
    projectId: 'appcatatan-258a2',
    storageBucket: 'appcatatan-258a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWRgteT2ur1FVpVLCN_BwB1P15lcr1BEs',
    appId: '1:489113225670:web:162de9f94a65ddc9030ac7',
    messagingSenderId: '489113225670',
    projectId: 'appcatatan-258a2',
    authDomain: 'appcatatan-258a2.firebaseapp.com',
    storageBucket: 'appcatatan-258a2.firebasestorage.app',
    measurementId: 'G-LF4XPQ71CK',
  );
}
